import { defineStore } from 'pinia';
import { ref, computed } from 'vue';
import { useAgent, type ChatMessage } from '../composables/useAgent';

const STORAGE_KEY = 'vibeeditor-agent-sessions';
const MSG_STORAGE_PREFIX = 'vibeeditor-agent-msgs-';

let sessionCounter = 0;

/** 会话元数据 —— 持久化到 localStorage */
export interface AgentSession {
  id: string;
  name: string;
  nameAutoGenerated: boolean;
  createdAt: number;
}

function isCJK(c: string): boolean {
  const code = c.charCodeAt(0);
  return (code >= 0x4e00 && code <= 0x9fff) || (code >= 0x3400 && code <= 0x4dbf);
}

function generateSessionName(text: string): string {
  const maxUnits = 20;
  let units = 0;
  let i = 0;
  for (i = 0; i < text.length; i++) {
    const char = text[i];
    if (char === '\n') break;
    units += isCJK(char) ? 2 : 1;
    if (units > maxUnits) break;
  }
  const name = text.slice(0, i).trim();
  if (!name) return '';
  return name.length < text.trim().length ? name + '...' : name;
}

function loadSessions(): AgentSession[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const data = JSON.parse(raw);
      if (Array.isArray(data)) return data;
    }
  } catch { /* corrupted data, ignore */ }
  return [];
}

function saveSessions(sessions: AgentSession[]) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(sessions));
  } catch { /* storage full or unavailable */ }
}

function saveMessages(sessionId: string, messages: ChatMessage[]) {
  try {
    localStorage.setItem(MSG_STORAGE_PREFIX + sessionId, JSON.stringify(messages));
  } catch { /* storage full */ }
}

function loadMessages(sessionId: string): ChatMessage[] {
  try {
    const raw = localStorage.getItem(MSG_STORAGE_PREFIX + sessionId);
    if (raw) {
      const data = JSON.parse(raw);
      if (Array.isArray(data)) return data;
    }
  } catch { /* corrupted data */ }
  return [];
}

function removeMessages(sessionId: string) {
  try {
    localStorage.removeItem(MSG_STORAGE_PREFIX + sessionId);
  } catch { /* ignore */ }
}

/**
 * 会话管理 store —— 管理多个 Agent 会话的标签页状态。
 * 每个会话对应一个独立的 useAgent() 实例。
 */
export const useSessionStore = defineStore('sessions', () => {
  // --- 从 localStorage 恢复（无数据时自动创建默认会话） ---
  const stored = loadSessions();
  if (stored.length > 0) {
    sessionCounter = stored.reduce((max, s) => {
      const num = parseInt(s.id.replace('session_', ''), 10);
      return Number.isFinite(num) && num > max ? num : max;
    }, 0);
  }

  const sessions = ref<AgentSession[]>(stored);

  // --- 非响应式 Map：会话 ID → useAgent 实例 ---
  const agents = new Map<string, ReturnType<typeof useAgent>>();

  // --- 响应式状态 ---
  const activeSessionId = ref<string | null>(sessions.value.length > 0 ? sessions.value[0].id : null);

  // --- 为已恢复的会话创建 useAgent 实例并恢复消息 ---
  for (const s of sessions.value) {
    const agent = useAgent(s.id);
    agents.set(s.id, agent);
    const msgs = loadMessages(s.id);
    if (msgs.length > 0) {
      agent.restoreMessages(msgs);
    }
  }

  // --- 无存储数据时自动创建默认会话 ---
  if (sessions.value.length === 0) {
    const id = `session_${++sessionCounter}`;
    const session: AgentSession = {
      id,
      name: '新会话',
      nameAutoGenerated: false,
      createdAt: Date.now(),
    };
    sessions.value.push(session);
    activeSessionId.value = id;
    agents.set(id, useAgent(id));
    saveSessions(sessions.value);
  }

  // --- Computed ---
  const activeSession = computed<AgentSession | null>(
    () => sessions.value.find(s => s.id === activeSessionId.value) ?? null
  );

  const activeAgent = computed(() => {
    const id = activeSessionId.value;
    return id ? agents.get(id) ?? null : null;
  });

  // --- Methods ---

  /** 创建新会话 —— 插入到数组最左侧 */
  function createSession(): AgentSession {
    const id = `session_${++sessionCounter}`;
    const session: AgentSession = {
      id,
      name: '新会话',
      nameAutoGenerated: false,
      createdAt: Date.now(),
    };
    sessions.value.unshift(session);
    activeSessionId.value = id;
    agents.set(id, useAgent(id));
    saveSessions(sessions.value);
    return session;
  }

  /** 关闭会话 —— 若关闭的是活跃会话则切换到相邻会话 */
  function closeSession(id: string) {
    const idx = sessions.value.findIndex(s => s.id === id);
    if (idx === -1) return;
    sessions.value.splice(idx, 1);
    agents.delete(id);
    removeMessages(id);

    if (activeSessionId.value === id) {
      if (sessions.value.length > 0) {
        const nextIdx = Math.min(idx, sessions.value.length - 1);
        activeSessionId.value = sessions.value[nextIdx].id;
      } else {
        activeSessionId.value = null;
      }
    }

    saveSessions(sessions.value);
  }

  /** 切换活跃会话 */
  function setActiveSession(id: string) {
    if (sessions.value.find(s => s.id === id)) {
      activeSessionId.value = id;
    }
  }

  /** 手动更新会话名称 */
  function updateSessionName(id: string, name: string) {
    const session = sessions.value.find(s => s.id === id);
    if (session) {
      session.name = name;
      session.nameAutoGenerated = false;
      saveSessions(sessions.value);
    }
  }

  /** 从首条用户消息自动生成会话名称 —— 仅在尚未自动命名时生效 */
  function autoNameFromFirstMessage(sessionId: string, message: string) {
    const session = sessions.value.find(s => s.id === sessionId);
    if (!session || session.nameAutoGenerated) return;
    const name = generateSessionName(message);
    if (name) {
      session.name = name;
      session.nameAutoGenerated = true;
      saveSessions(sessions.value);
    }
  }

  /** 持久化当前活跃会话的消息历史 */
  function saveCurrentSession() {
    const id = activeSessionId.value;
    if (!id) return;
    const agent = agents.get(id);
    if (agent) {
      saveMessages(id, agent.messages.value);
    }
  }

  return {
    sessions,
    activeSessionId,
    activeSession,
    activeAgent,
    createSession,
    closeSession,
    setActiveSession,
    updateSessionName,
    autoNameFromFirstMessage,
    saveCurrentSession,
  };
});
